// Seed data based on James's actual thesis proposal timeline

export const milestonesSeed = [
  // February: System Build & Stabilization
  {
    title: 'Core RAG pipeline — document ingestion & chunking',
    description: 'Implement document ingestion, sliding-window chunking, and vectorization with text-embedding-3-small into Pinecone',
    phase: 'build',
    due_date: '2026-02-15',
    week_start: '2026-02-09',
    week_end: '2026-02-15',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Retrieval + citation engine functional',
    description: 'RAG retrieval working with citation linking — every AI claim tied to an excerpt from evidence packets',
    phase: 'build',
    due_date: '2026-02-22',
    week_start: '2026-02-16',
    week_end: '2026-02-22',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'UX for citations, evidence snippets & uncertainty flags',
    description: 'Implement citation engine UI, confidence transparency visual cues, clickable citations linking to source documents',
    phase: 'build',
    due_date: '2026-02-28',
    week_start: '2026-02-23',
    week_end: '2026-03-01',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Internal QA with known-answer scenario tests',
    description: 'Validate citation behavior using scenario packets, conduct QA with known-answer tests. Build complete & stable, test script locked.',
    phase: 'build',
    due_date: '2026-03-01',
    week_start: '2026-02-23',
    week_end: '2026-03-01',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: false,
  },

  // March: Data Collection
  {
    title: 'Recruit participants',
    description: 'Recruit from online professional communities and networks. Target N=20-30, balanced across conditions. Screen for school safety/risk-related experience.',
    phase: 'data-collection',
    due_date: '2026-03-15',
    week_start: '2026-03-02',
    week_end: '2026-03-15',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Run usability sessions (think-aloud + task completion)',
    description: 'Between-subjects study: control (manual) vs treatment (RAG assistant). Collect time-on-task, form data, interaction logs.',
    phase: 'data-collection',
    due_date: '2026-03-29',
    week_start: '2026-03-16',
    week_end: '2026-03-29',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Collect surveys & organize datasets',
    description: 'Post-task questionnaires (TTF, SUS, cognitive workload, trust), semi-structured interviews. Save all interaction logs and participant artifacts.',
    phase: 'data-collection',
    due_date: '2026-03-31',
    week_start: '2026-03-30',
    week_end: '2026-03-31',
    status: 'not_started',
    priority: 'important',
    advisor_deliverable: false,
  },

  // April: Analysis & Results
  {
    title: 'Quantitative analysis',
    description: 'Descriptive stats, t-tests/Mann-Whitney U, effect sizes (Cohen\'s d). Analyze time, errors, task success, survey scales.',
    phase: 'analysis',
    due_date: '2026-04-15',
    week_start: '2026-04-01',
    week_end: '2026-04-15',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Qualitative analysis & grounding quality scoring',
    description: 'Thematic coding of usability issues, trust calibration moments. Score grounding quality rubric, inter-rater agreement.',
    phase: 'analysis',
    due_date: '2026-04-22',
    week_start: '2026-04-16',
    week_end: '2026-04-22',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Write Results section',
    description: 'Include key figures/tables, representative quotes. Triangulate with interaction logs.',
    phase: 'analysis',
    due_date: '2026-04-30',
    week_start: '2026-04-23',
    week_end: '2026-04-30',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },

  // May: Discussion & Introduction
  {
    title: 'Write Discussion section',
    description: 'Interpretation, implications for RAG in risk workflows, design recommendations.',
    phase: 'writing',
    due_date: '2026-05-15',
    week_start: '2026-05-01',
    week_end: '2026-05-15',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Write Introduction section',
    description: 'Problem framing, research questions, contributions, study overview.',
    phase: 'writing',
    due_date: '2026-05-25',
    week_start: '2026-05-16',
    week_end: '2026-05-25',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Tighten Related Work / Literature Review',
    description: 'Update to match what Results and Discussion emphasize.',
    phase: 'writing',
    due_date: '2026-05-31',
    week_start: '2026-05-26',
    week_end: '2026-05-31',
    status: 'not_started',
    priority: 'important',
    advisor_deliverable: true,
  },

  // June: Final Draft & Defense
  {
    title: 'Full revision pass',
    description: 'Clarity, cohesion, formatting. Integrate advisor/committee feedback.',
    phase: 'defense',
    due_date: '2026-06-15',
    week_start: '2026-06-01',
    week_end: '2026-06-15',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: true,
  },
  {
    title: 'Final figures, appendices & defense prep',
    description: 'Scenario cards, evidence packets, rubrics, scripts. Prepare defense presentation.',
    phase: 'defense',
    due_date: '2026-06-22',
    week_start: '2026-06-16',
    week_end: '2026-06-22',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: false,
  },
  {
    title: '🎓 THESIS DEFENSE',
    description: 'Final draft submitted and defense completed.',
    phase: 'defense',
    due_date: '2026-06-28',
    week_start: '2026-06-23',
    week_end: '2026-06-28',
    status: 'not_started',
    priority: 'critical',
    advisor_deliverable: false,
  },
]

export const writingSectionsSeed = [
  { title: 'Abstract', chapter_order: 0, status: 'complete', target_word_count: 300, current_word_count: 280 },
  { title: 'Introduction', chapter_order: 1, status: 'not_started', target_word_count: 3000, current_word_count: 0, due_date: '2026-05-25' },
  { title: 'Literature Review', chapter_order: 2, status: 'in_progress', target_word_count: 5000, current_word_count: 1200, due_date: '2026-05-31' },
  { title: 'Methodology', chapter_order: 3, status: 'not_started', target_word_count: 4000, current_word_count: 0, due_date: '2026-04-30' },
  { title: 'Results', chapter_order: 4, status: 'not_started', target_word_count: 4000, current_word_count: 0, due_date: '2026-04-30' },
  { title: 'Discussion', chapter_order: 5, status: 'not_started', target_word_count: 3000, current_word_count: 0, due_date: '2026-05-15' },
  { title: 'Conclusion', chapter_order: 6, status: 'not_started', target_word_count: 1500, current_word_count: 0, due_date: '2026-06-15' },
  { title: 'References', chapter_order: 7, status: 'in_progress', target_word_count: null, current_word_count: 0 },
  { title: 'Appendices', chapter_order: 8, status: 'not_started', target_word_count: null, current_word_count: 0, due_date: '2026-06-22' },
]

export const papersSeed = [
  {
    title: 'Task-technology fit and individual performance',
    authors: 'Goodhue, D. L., & Thompson, R. L.',
    year: 1995,
    source: 'MIS Quarterly',
    doi: '10.2307/249689',
    tags: ['TTF', 'kernel-theory'],
    summary: 'Foundational TTF paper arguing technology improves individual performance when capabilities match task demands and user needs.',
    relevance_notes: 'Kernel theory for the thesis. TTF used to evaluate whether RAG-based assistant improves perceived fit vs static tools.',
  },
  {
    title: 'Design science in information systems research',
    authors: 'Hevner, A. R., March, S. T., Park, J., & Ram, S.',
    year: 2004,
    source: 'MIS Quarterly',
    doi: '10.2307/25148625',
    tags: ['DSR', 'methodology'],
    summary: 'Seminal DSR framework paper establishing guidelines for design science research in IS.',
    relevance_notes: 'Primary research framework. Thesis follows DSR with three cycles.',
  },
  {
    title: 'Trust in automation: Designing for appropriate reliance',
    authors: 'Lee, J. D., & See, K. A.',
    year: 2004,
    source: 'Human Factors',
    doi: '10.1518/hfes.46.1.50.30392',
    tags: ['trust', 'calibration', 'human-AI'],
    summary: 'Describes calibrated trust as alignment between user trust and system actual capabilities.',
    relevance_notes: 'Trust calibration is a design requirement — users should verify AI claims and decide when to rely on vs override the system.',
  },
  {
    title: 'Retrieval-augmented generation for knowledge-intensive NLP tasks',
    authors: 'Lewis, P. et al.',
    year: 2020,
    source: 'NeurIPS',
    tags: ['RAG', 'architecture'],
    summary: 'Introduces RAG approach combining retrieval with generation for knowledge-grounded responses.',
    relevance_notes: 'Core architecture pattern. Scaffolding is implemented through RAG pipeline that retrieves policy excerpts to ground responses.',
  },
  {
    title: 'Mind in society: The development of higher psychological processes',
    authors: 'Vygotsky, L. S.',
    year: 1978,
    source: 'Harvard University Press',
    tags: ['scaffolding', 'education', 'theory'],
    summary: 'Foundational work on scaffolding and zone of proximal development in learning theory.',
    relevance_notes: 'Theoretical basis for scaffolding design — guided progression from novice to expert performance.',
  },
  {
    title: 'Mapping a design science research cycle to the postgraduate research report',
    authors: 'Van der Merwe, A., Gerber, A., & Smuts, H.',
    year: 2017,
    source: 'SAICSIT Proceedings',
    doi: '10.1145/3129416.3129437',
    tags: ['DSR', 'methodology'],
    summary: 'Describes Scenario 2: Multiple Cycles model for structuring DSR with distinct development and testing of different components.',
    relevance_notes: 'Study is structured according to this multiple cycles model.',
  },
  {
    title: 'Does AI reliance lead to performance? A task-technology fit theory perspective',
    authors: 'Dharanikota, S., & Marakas, G. M.',
    year: 2023,
    source: 'Journal of Computer Information Systems',
    doi: '10.1080/08874417.2021.1996967',
    tags: ['TTF', 'AI', 'evaluation'],
    summary: 'Examines AI reliance through TTF lens, evaluating whether RAG-based assistance improves perceived TTF and task outcomes.',
    relevance_notes: 'Directly supports evaluation approach — comparing RAG-based assistant vs static form and manual document review.',
  },
  {
    title: 'The role of technology in improving K-12 school safety',
    authors: 'Schwartz, H. L. et al.',
    year: 2016,
    source: 'RAND Corporation',
    doi: '10.7249/RR1488',
    tags: ['K-12', 'school-safety', 'domain'],
    summary: 'Examines technology role in school safety, noting uncertainty about effective measures and evaluation challenges.',
    relevance_notes: 'Supports expertise gap argument — schools face uncertainty about which safety measures are effective.',
  },
  {
    title: 'Notes from the field: The value of school safety assessments',
    authors: 'National Institute of Justice',
    year: 2022,
    source: 'U.S. Department of Justice',
    tags: ['K-12', 'school-safety', 'risk-assessment'],
    summary: 'NIJ report on the importance and methodology of school safety assessments.',
    relevance_notes: 'Supports need for systematic risk assessment in K-12 settings.',
  },
  {
    title: 'SUS: A "quick and dirty" usability scale',
    authors: 'Brooke, J.',
    year: 1996,
    source: 'Usability evaluation in industry, Taylor & Francis',
    tags: ['usability', 'SUS', 'evaluation'],
    summary: 'Introduces the System Usability Scale, a reliable 10-item scale for usability assessment.',
    relevance_notes: 'Primary usability measure for evaluation study.',
  },
]
